### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by dragonblz** [ItsDrike/code-jam-2024#37]
ValueError: invalid literal for int() with base 10: 'list-8116'
gives this error when i tried to do avatar the last airbender and didnt add the : sign

**Comment by ItsDrike** [comment]
Managed to reproduce this, here's the traceback:

```python
Traceback (most recent call last):
  File "/home/itsdrike/Personal/Programming/Python/Projects/Bigger/code-jam-2024/.venv/lib/python3.12/site-packages/discord/commands/core.py", line 138, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/home/itsdrike/Personal/Programming/Python/Projects/Bigger/code-jam-2024/.venv/lib/python3.12/site-packages/discord/commands/core.py", line 1078, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/home/itsdrike/Personal/Programming/Python/Projects/Bigger/code-jam-2024/src/exts/tvdb_info/main.py", line 103, in search
    response = await client.search(query, limit=5)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itsdrike/Personal/Programming/Python/Projects/Bigger/code-jam-2024/src/tvdb/client.py", line 211, in search
    return [Movie(self, result) if result.id[0] == "m" else Series(self, result) for result in response.data]
                                                            ^^^^^^^^^^^^^^^^^^^^
  File "/home/itsdrike/Personal/Programming/Python/Projects/Bigger/code-jam-2024/src/tvdb/client.py", line 51, in __init__
    self.id = self.data.id
    ^^^^^^^
  File "/home/itsdrike/Personal/Programming/Python/Projects/Bigger/code-jam-2024/src/tvdb/client.py", line 96, in id
    self._id = parse_media_id(value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/itsdrike/Personal/Programming/Python/Projects/Bigger/code-jam-2024/src/tvdb/client.py", line 35, in parse_media_id
    return int(str(media_id).removeprefix("movie-").removeprefix("series-"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'list-8116'
```

**Comment by ItsDrike** [comment]
CC @Paillat-dev
